/**
 * Quiet-{Palette} is exposed wherever Text-{Palette} is.
 *
 * The Modes collection has held the whole table all along: Quiet/Surfaces and
 * Quiet/Containers each cover BW, Error, Hotlink-Visited, Info, Neutral,
 * Primary, Secondary, Success, Tertiary and Warning — scope for scope with
 * Text, 240 variables against Text's 265, the difference being one extra
 * BW-Button scope rather than nine missing palettes.
 *
 * Only one palette's worth was ever exposed. So Text-{Palette} shipped nine
 * siblings and Quiet shipped alone, and a muted label in a palette's hue had no
 * token to reach for — which is why a disabled outline button had to borrow the
 * fill-checked Buttons-{C}-Quiet, a colour measured against a fill it does not
 * have.
 *
 * The tone is the invariant, not the value: each Quiet-{Palette} reads the same
 * Color-N as the Text-{Palette} beside it. That is what "same tone as Quiet"
 * means, and it is why this needs no new contrast solving — the index is the
 * one the curated table already chose.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';

const SRC = fs.readFileSync(
  path.join(__dirname, '..', 'utils', 'cssgen', 'exportColorSystem.ts'), 'utf8');

const PALETTES = ['Primary', 'Secondary', 'Tertiary', 'Neutral',
                  'Info', 'Success', 'Warning', 'Error'];

describe('Quiet is exposed per palette', () => {
  it('emits a Quiet-{Palette} for every palette Text has', () => {
    const missing = PALETTES.filter((p) => !SRC.includes(`'Quiet-${p}':`));
    expect(missing).toEqual([]);
  });

  it('reads the Quiet table, not the Text table', () => {
    /* The distinction the whole slot exists for. Pointing these at
       {Text.…} would resolve, render a real colour, and silently make the
       muted role identical to the loud one. */
    for (const p of PALETTES) {
      const line = SRC.match(new RegExp(`'Quiet-${p}': \\{ value: \`([^\`]+)\``))?.[1] || '';
      expect(`${p} source: ${line.startsWith('{Quiet.')}`).toBe(`${p} source: true`);
    }
  });

  it('takes the SAME tone as the Text row beside it', () => {
    /* "Quiet-* has the same tone as Quiet for all the colors" — the design
       owner's rule, and the reason no new contrast work is needed. If these
       ever drift to a different Color-N the pair stops being one tone and the
       curated table's guarantee no longer transfers. */
    for (const p of PALETTES) {
      const q = SRC.match(new RegExp(`'Quiet-${p}': \\{ value: \`\\{Quiet\\.\\w+\\.[^.]+\\.(Color-[^}]+)\\}`))?.[1];
      const t = SRC.match(new RegExp(`'Text-${p}': \\{ value: \`\\{Text\\.\\w+\\.[^.]+\\.(Color-[^}]+)\\}`))?.[1];
      expect(`${p} tone q=${q} t=${t}`).toBe(`${p} tone q=${t} t=${t}`);
    }
  });

  it('covers Surfaces AND Containers', () => {
    /* A card is a Container. Exposing only Surfaces would leave every muted
       palette label inside a card reaching for a surface-scoped value. */
    expect(SRC).toMatch(/'Quiet-Primary': \{ value: `\{Quiet\.Surfaces\./);
    expect(SRC).toMatch(/'Quiet-Primary': \{ value: `\{Quiet\.Containers\./);
  });
});

describe('the Default theme routes Quiet accents through Default-Background', () => {
  const THEMES = fs.readFileSync(
    path.join(__dirname, '..', 'utils', 'cssgen', 'generateCompleteThemes.ts'), 'utf8');

  it('names Quiet-{Palette} alongside Text and Header', () => {
    /* DEFAULT_BG_ROLES spelled out Text-{Palette} and Header-{Palette} and
       listed Quiet once, bare. So the Default theme could route a primary TEXT
       and a primary HEADER through Default-Background and had nowhere to send a
       primary QUIET — the muted role was the only one of the three that could
       not speak in a palette's hue.

       Asserted on the LIST rather than on output: the three are generated by
       the same map, so a missing one is a missing line here and nothing
       downstream can tell you which role was left out. */
    for (const role of ['Text', 'Header', 'Quiet']) {
      expect(`${role} accents mapped: ${THEMES.includes('`' + role + '-${p}`')}`)
        .toBe(`${role} accents mapped: true`);
    }
  });
});
