/**
 * No component asks for a theme the generator does not emit.
 *
 * `src/utils/themes.ts` records why the shades went: a shade and a surface
 * level were two ways of saying one thing, and four modes per palette is 33
 * where Figma caps a collection at 10. `Primary-Light` is now
 * `data-theme="Primary"` + `data-surface="Surface-Brightest"`.
 *
 * Nothing enforced it, and three usages survived in the landing pages. The
 * failure is silent in the worst way: an unmatched `[data-theme="X"]` selector
 * is not an error, so the element simply inherits whatever is above it. The
 * section reads as unthemed rather than broken, and `Neutral-Dark` had been
 * painting a LIGHT band where a dark one was intended.
 *
 * Measured at the time of the fix, against the live stylesheet:
 *   Neutral-Dark / Surface        -> every token UNDEFINED
 *   Primary-Light / Container     -> --Background UNDEFINED (text and border resolved)
 * which is why this checks the NAME rather than trusting that a wrong one looks wrong.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { THEME_MODES, CSS_ONLY_THEMES } from '../utils/themes';

const SRC = join(__dirname, '..', 'components');

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) return walk(full);
    return /\.tsx?$/.test(name) ? [full] : [];
  });
}

/* Valid in a data-theme beyond the Theme collection's own modes.
   The bar themes are NOT in that collection — they are CSS-only by design
   (CSS_ONLY_THEMES in ../utils/themes: a bar is a composition of a user pick,
   and Figma pins a mode on the bar's frame instead). This read the other way
   round until it was checked: "the Theme collection carries" them, which is
   the claim generateFigmaJSON's own warning appeared to confirm. Imported now
   rather than retyped, so the list cannot drift from the one that defines it. */
const EXTRA = [...CSS_ONLY_THEMES, 'Brand', 'Default'];

describe('theme names the components ask for', () => {
  const files = walk(SRC);

  it('finds component files to check', () => {
    expect(files.length).toBeGreaterThan(20);
  });

  it('no component uses a -Light / -Medium / -Dark theme name', () => {
    const bad: string[] = [];
    for (const f of files) {
      const src = readFileSync(f, 'utf8');
      for (const m of src.matchAll(/(?:data-)?theme=["'`]([A-Za-z-]+)["'`]/g)) {
        if (/-(Light|Medium|Dark)$/.test(m[1])) {
          bad.push(`${f.replace(SRC, 'components')}: theme="${m[1]}"`);
        }
      }
    }
    expect(bad, 'A shade is a SURFACE level now — use the bare theme plus '
      + 'data-surface (Surface-Brightest for Light, Surface-Dimmest for Dark). '
      + 'An unmatched [data-theme] selector paints nothing and inherits silently.')
      .toEqual([]);
  });

  it('every literal theme name is one the generator emits', () => {
    const valid = new Set<string>([...(THEME_MODES as readonly string[]), ...EXTRA]);
    const bad: string[] = [];
    for (const f of files) {
      const src = readFileSync(f, 'utf8');
      for (const m of src.matchAll(/(?:data-)?theme=["']([A-Za-z][A-Za-z-]*)["']/g)) {
        const name = m[1];
        // Brand-* are the preview's own scopes, generated by buildPreviewCSS.
        if (name.startsWith('Brand')) continue;
        if (!valid.has(name)) bad.push(`${f.replace(SRC, 'components')}: theme="${name}"`);
      }
    }
    expect(bad, 'Not a mode in THEME_MODES — see src/utils/themes.ts').toEqual([]);
  });
});
