/**
 * The last batch: the Select family, and the components with no Figma page.
 *
 * The undesigned ones still get a full doc. A component missing from the
 * reference is indistinguishable from one an agent has not found, so each says
 * plainly that there is no drawing and to build from the props — which the
 * renderer emits as its own line rather than an empty Figma section.
 */
import type { ComponentDoc } from './componentDoc';

const surfaceToken = (name: string, sets: string) =>
  ({ name, sets, variesWith: 'theme + surface', figma: 'Modes → Theme → Surface' });
const inherits = (what = 'an ancestor') => ([{
  collection: 'Theme' as const,
  inCode: `\`data-theme\` on ${what}.`,
  inFigma: 'No Figma counterpart — it inherits whatever zone it is dropped into.',
}]);

export const SELECT_DOC: ComponentDoc = {
  name: 'Select',
  summary: 'Picks one or more values from a fixed list.',
  insteadUse: [
    { when: 'The user types and the list narrows', use: 'Autocomplete' },
    { when: 'There are five or fewer options', use: 'RadioGroup' },
    { when: 'The list is actions, not values', use: 'Menu' },
  ],
  props: [
    { name: 'options', type: 'array', default: '[]' },
    { name: 'defaultValue', type: 'string', default: "''" },
    { name: 'label', type: 'string', default: 'undefined' },
    { name: 'labelPosition', type: 'string', values: ['top', 'floating'], default: 'top' },
    { name: 'variant', type: 'string', default: 'outline', note: 'The `light` variant was removed — see the Button note on `-light`.' },
    { name: 'color', type: 'string', default: 'primary' },
    { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' },
    { name: 'mode', type: 'string', values: ['standard', 'multiselect', 'searchable'], default: 'standard' },
  ],
  states: [
    { state: 'Hover', setBy: 'interaction' },
    { state: 'Pressed', setBy: 'interaction' },
    { state: 'Focus-visible', setBy: 'interaction' },
    { state: 'Open', setBy: 'interaction' },
    { state: 'Disabled', setBy: 'prop' },
  ],
  theming: [
    { collection: 'Theme', inCode: '`data-theme` on an ancestor.',
      inFigma: 'Neither `Select` nor `SelectMenu` pins a Theme mode. Set it on the frame around them.' },
  ],
  themingNotes: [
    'In Figma the trigger and the panel are separate sets: `Select` is a Button instance with `type = default | multiselect | searchable`, `SelectMenu` is the panel it opens — and the panel is itself a TreeView instance built from Menu Item.',
  ],
  tokens: [
    surfaceToken('--Border', 'the trigger outline'),
    surfaceToken('--Text', 'the chosen value'),
    surfaceToken('--Quiet', 'the placeholder'),
    { name: '--Input-Height', sets: 'the trigger height', variesWith: 'size mode + device', figma: 'Input/Input-Height' },
    { name: '--Dropdown-Frame-Radius', sets: 'the panel corner', variesWith: 'size mode', figma: 'Menu/Dropdown-Frame-Radius' },
  ],
  composition: ['Options are data. The panel is the component’s own — do not place a Menu beside it.'],
  accessibility: [
    'It needs a label. A select showing "Choose…" with no label is unlabelled.',
    'Arrow keys move through options, Enter picks, Escape closes without changing the value.',
    'Multiselect must announce how many are chosen, not just the first.',
  ],
  gotchas: [
    '`--Dropdown-Frame-Radius` is `min(Input-Radius, Card-Radius, 16px)` in pixels, not a percent: the panel follows the input it opens from, is never rounder than the cards it floats above, and caps at 16 because rows are full-bleed and a larger corner clips the first and last row’s hover.',
  ],
};

export const MENU_DOC: ComponentDoc = {
  name: 'Menu',
  summary: 'A list of actions opened from a control.',
  insteadUse: [
    { when: 'It picks a value for a form', use: 'Select' },
    { when: 'It is permanent navigation', use: 'Rail or Sidebar' },
    { when: 'It holds arbitrary content, not a list', use: 'Popover' },
  ],
  props: [
    { name: 'variant', type: 'string', default: 'outline' },
    { name: 'color', type: 'string', default: 'default' },
    { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' },
  ],
  states: [
    { state: 'Open', setBy: 'context', note: 'From the `Dropdown` root, which owns the state.' },
    { state: 'Hover / Focus-visible', setBy: 'interaction', note: 'Per item.' },
    { state: 'Disabled', setBy: 'prop', note: 'Per `MenuItem`.' },
  ],
  theming: [
    { collection: 'Theme', inCode: '`data-theme` on an ancestor.',
      inFigma: '`Menu Item` pins nothing and inherits. It has its own page because TreeView and SelectMenu both build from it.' },
  ],
  tokens: [
    surfaceToken('--Background', 'the panel'),
    surfaceToken('--Hover', 'row hover'),
    { name: '--Dropdown-Frame-Radius', sets: 'the panel corner', variesWith: 'size mode', figma: 'Menu/Dropdown-Frame-Radius' },
    { name: '--Menu-Item-Radius', sets: 'a row corner', variesWith: 'size mode', figma: 'Menu/Menu-Item-Radius' },
  ],
  composition: [
    'Always `<Dropdown>` as the root — it supplies the open state through context. A `<Menu>` on its own reads the default context, whose `open` is false, so it renders NOTHING with no warning.',
    'Then `<MenuButton>` as the trigger and `<MenuItem>` / `<MenuDivider>` inside.',
  ],
  accessibility: [
    'The trigger carries `aria-haspopup`, `aria-expanded` and `aria-controls`; the panel is a `menu` of `menuitem`s. All handled.',
    'Arrow keys move, Escape closes and returns focus to the trigger.',
  ],
  gotchas: [
    '**It does not portal.** The panel is `position: absolute` inside the Dropdown wrapper, and z-index cannot lift a positioned element out of an `overflow: hidden` or transformed ancestor — so inside a scrolling container or a clipped card it is cut off. Use the portal pattern for those, and tag it `MISSING-LIB-COMPONENT: Popover`.',
    'Its 18 failing ARIA tests are TEST bugs: they assert on `getByText(...)`, which returns the inner Typography `<p>`, while the ARIA attributes are correctly on the ancestor `<button>`. Do not "fix" the component to satisfy them.',
  ],
};

const undesigned = (
  name: string, summary: string,
  insteadUse: ComponentDoc['insteadUse'],
  props: ComponentDoc['props'],
  states: ComponentDoc['states'],
  tokens: ComponentDoc['tokens'],
  composition: string[], accessibility: string[], gotchas: string[],
): ComponentDoc => ({
  name, summary, insteadUse, props, states,
  theming: inherits(), tokens, composition, accessibility, gotchas,
});

export const REST_DOCS: ComponentDoc[] = [
  SELECT_DOC,
  MENU_DOC,

  undesigned('Autocomplete',
    'A text field whose list narrows as the user types.',
    [{ when: 'The list is short and fixed', use: 'Select' },
     { when: 'It searches a page rather than picking a value', use: 'SearchField' }],
    [{ name: 'options', type: 'array', default: '[]' },
     { name: 'defaultValue', type: 'object', default: 'null' },
     { name: 'placeholder', type: 'string', default: "'Type to search'" },
     { name: 'label', type: 'string', default: 'undefined' },
     { name: 'labelPosition', type: 'string', values: ['top', 'floating'], default: 'top' },
     { name: 'variant', type: 'string', default: 'outline' },
     { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' }],
    [{ state: 'Focus-visible', setBy: 'interaction' },
     { state: 'Open', setBy: 'interaction', note: 'Opens as the user types, not on focus.' },
     { state: 'Disabled', setBy: 'prop' }],
    [surfaceToken('--Border', 'the field outline'), surfaceToken('--Background', 'the suggestion panel')],
    ['Options are data. The panel is the component’s own.'],
    ['The suggestion list must be announced as it changes — a silently updating list is invisible to a screen reader.',
     'Arrow keys move through suggestions without losing what has been typed.'],
    ['No Figma drawing. Its trigger is a text field and its panel matches SelectMenu — build from those two rather than inventing a third.']),

  undesigned('TextField',
    'One line of typed text. The lower-level field that Input builds on.',
    [{ when: 'You want the full field with label and validation', use: 'Input' },
     { when: 'More than one line', use: 'TextArea' }],
    [{ name: 'label', type: 'string', default: 'undefined' },
     { name: 'value', type: 'string', default: "''" },
     { name: 'placeholder', type: 'string', default: 'undefined' },
     { name: 'error', type: 'boolean', default: 'false' },
     { name: 'errorMessage', type: 'string', default: "''" },
     { name: 'helperText', type: 'string', default: "''" },
     { name: 'variant', type: 'string', default: 'outlined' },
     { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' }],
    [{ state: 'Focus-visible', setBy: 'interaction' },
     { state: 'Error', setBy: 'prop' },
     { state: 'Disabled', setBy: 'prop' }],
    [surfaceToken('--Border', 'the outline'), surfaceToken('--Text', 'the value')],
    ['Label, helper and error are props — the wiring is what makes them announced with the field.'],
    ['Every field needs a label; a placeholder is not one, because it disappears on focus.',
     '`error` should set `aria-invalid` and tie the message with `aria-describedby`.'],
    ['Prefer `Input`, which is the designed one. TextField exists for cases Input’s API does not reach.']),

  undesigned('SearchField',
    'A field for searching, with a clear button and a submit.',
    [{ when: 'It picks from a fixed list', use: 'Select or Autocomplete' },
     { when: 'It is a general text field', use: 'Input' }],
    [{ name: 'defaultValue', type: 'string', default: "''" },
     { name: 'placeholder', type: 'string', default: "'Search…'" },
     { name: 'showClearButton', type: 'boolean', default: 'true' },
     { name: 'onSubmit', type: 'function', default: 'undefined' },
     { name: 'onClear', type: 'function', default: 'undefined' },
     { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' },
     { name: 'color', type: 'string', default: 'default' }],
    [{ state: 'Focus-visible', setBy: 'interaction' },
     { state: 'Has value', setBy: 'interaction', note: 'Reveals the clear button.' }],
    [surfaceToken('--Border', 'the outline'), surfaceToken('--Quiet', 'the placeholder and icon')],
    ['The search icon and clear button are the component’s own — do not add decorators for them.'],
    ['The clear button needs a name — "Clear search", not an X.',
     'It should be a `<form>` with `role="search"` so it can be jumped to as a landmark.'],
    ['No Figma drawing. It is an Input with two fixed decorators; build it from the Input design.']),

  undesigned('Popover',
    'A floating panel anchored to an element, holding arbitrary content.',
    [{ when: 'It is a list of actions', use: 'Menu' },
     { when: 'It is a short label on hover', use: 'Tooltip' },
     { when: 'It blocks the page', use: 'Modal' }],
    [{ name: 'open', type: 'boolean', default: 'false' },
     { name: 'anchorRef', type: 'ref', default: 'undefined' },
     { name: 'placement', type: 'string', default: 'bottom-end' },
     { name: 'theme', type: 'string', default: 'Default' },
     { name: 'surface', type: 'string', default: 'Surface-Bright' },
     { name: 'width', type: 'number', default: '320' },
     { name: 'maxHeight', type: 'number', default: '400' }],
    [{ state: 'Open', setBy: 'prop' }],
    [surfaceToken('--Background', 'the panel'), surfaceToken('--Border', 'its edge')],
    ['Anchored with `anchorRef` rather than by nesting, which is what lets it escape a clipped ancestor.'],
    ['It must close on Escape and on outside click, and return focus to whatever opened it.',
     'A popover containing controls needs focus moved into it; one holding only text does not.'],
    ['**This is the portal-based panel the Menu cannot be.** Menu is `position: absolute` and gets clipped inside a scrolling container; Popover portals to the body. It is also the component `MISSING-LIB-COMPONENT: Popover` refers to.',
     'It takes `theme` and `surface` directly, unlike most components — a floating panel has no ancestor to inherit a zone from once it portals.']),

  undesigned('Paper',
    'A plain raised surface. The unopinionated version of Card.',
    [{ when: 'It holds grouped content with padding', use: 'Card' },
     { when: 'It is a page region', use: 'Section' }],
    [{ name: 'surface', type: 'string', default: 'Container' },
     { name: 'outlined', type: 'boolean', default: 'false' },
     { name: 'variant', type: 'string', values: ['elevation', 'outlined'], default: 'elevation' }],
    [{ state: 'None', setBy: 'prop' }],
    [surfaceToken('--Background', 'the surface'), surfaceToken('--Border', 'the outline when outlined')],
    ['Children are yours entirely — Paper adds a surface and nothing else, not even padding.'],
    ['It is a region, not a control. Do not give it a role.'],
    ['Prefer `Card`, which is designed and carries padding and radius. Paper is for cases where you want the surface without the opinions.']),

  undesigned('Sidebar',
    'A wide panel of navigation down the side, usually with nested sections.',
    [{ when: 'It is narrow and icon-led', use: 'Rail' },
     { when: 'It slides in and is dismissed', use: 'Drawer' }],
    [{ name: 'items', type: 'array', default: '[]' },
     { name: 'width', type: 'number', default: '280' },
     { name: 'variant', type: 'string', values: ['temporary', 'permanent'], default: 'temporary' },
     { name: 'header', type: 'ReactNode', default: 'undefined' },
     { name: 'footer', type: 'ReactNode', default: 'undefined' }],
    [{ state: 'Open', setBy: 'prop', note: 'Only meaningful when temporary.' },
     { state: 'Selected', setBy: 'context' }],
    [surfaceToken('--Background', 'the panel'), surfaceToken('--Hover', 'item hover')],
    ['Items are data, with header and footer as slots.'],
    ['A `<nav>` of links with `aria-current` on the active one.',
     'A temporary sidebar traps focus; a permanent one must not.'],
    ['No Figma drawing. The Rail page has `Nav Rail`, `Nav Rail Item` and `Drawer Title`, which is the closest design — a sidebar is a rail that stays expanded.']),

  undesigned('Toolbar',
    'A row of actions belonging to a region or a selection.',
    [{ when: 'It is the top-level application bar', use: 'AppBar' },
     { when: 'It is one set of exclusive choices', use: 'ButtonGroup' }],
    [{ name: 'items', type: 'array', default: '[]' },
     { name: 'type', type: 'string', values: ['floating', 'docked'], default: 'floating' },
     { name: 'orientation', type: 'string', values: ['horizontal', 'vertical'], default: 'horizontal' },
     { name: 'color', type: 'string', default: 'default' },
     { name: 'fab', type: 'object', default: 'undefined' }],
    [{ state: 'Hover / Focus-visible', setBy: 'interaction', note: 'Per item.' },
     { state: 'Selected', setBy: 'prop' }],
    [surfaceToken('--Background', 'the bar'), surfaceToken('--Hover', 'item hover')],
    ['Items are data. A FAB comes from `fab` rather than being nested.'],
    ['Icon-only items each need a name saying the action.',
     'A toolbar is a `toolbar` role with arrow-key navigation between items, and one tab stop for the whole thing.'],
    ['No Figma drawing. `AppBar` shares its elevation group — AppBar, Toolbars and Menus are one row in the elevation table.']),

  undesigned('CodeBlock',
    'A block of code or a copyable command, with its own copy button.',
    [{ when: 'It is inline code in a sentence', use: 'a `code` element' },
     { when: 'It is editable', use: 'TextArea' }],
    [{ name: 'code', type: 'string', default: "''" },
     { name: 'language', type: 'string', default: 'JSX', note: 'Shown as a header label — `bash`, `JSX`, `CSS`, `URL`.' },
     { name: 'showCopy', type: 'boolean', default: 'true' },
     { name: 'showHeader', type: 'boolean', default: 'true' },
     { name: 'maxHeight', type: 'number', default: 'undefined' },
     { name: 'wrap', type: 'boolean', default: 'false' }],
    [{ state: 'Copied', setBy: 'interaction', note: 'The component owns the confirmation and its timer.' }],
    [{ name: '--Background', sets: 'the dark region', variesWith: 'theme + surface', figma: 'Modes → Theme → Surface' }],
    ['Code goes in `code`, not as children. The copy button is built in — do not add one.'],
    ['The copy button needs a name and its confirmation must be announced, not only drawn.'],
    ['Its dark region is NOT a hardcoded colour: it declares `data-theme="Neutral"` + `data-surface="Surface-Dimmest"`, so it follows the brand’s own neutrals and stays legible in both modes. Do not override its background.',
     'It brings its own copy state and timer, so the surrounding component must not keep a `copied` flag.']),

  undesigned('IconBadge',
    'An icon with a badge already positioned on it.',
    [{ when: 'You are badging something else', use: 'Badge around it' },
     { when: 'There is no badge', use: 'Icon' }],
    [{ name: 'color', type: 'string', default: 'primary' },
     { name: 'variant', type: 'string', default: 'solid' },
     { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' }],
    [{ state: 'None', setBy: 'prop' }],
    [{ name: '--Icons-{Color}', sets: 'the glyph', variesWith: 'theme + surface', figma: 'Icons → Icon' }],
    ['The icon is the child; the badge is the component’s own.'],
    ['The badge number means nothing alone — the accessible name must carry both, "Messages, 3 unread".'],
    ['No Figma drawing, but both halves are designed: `Icon` and `Badge Counter`. It is those two composed, not a third thing.']),

  undesigned('DropZone',
    'An area that accepts dropped or chosen files.',
    [{ when: 'It is a plain file input', use: 'an input of type file' },
     { when: 'It is an image placeholder', use: 'ImagePlaceholder' }],
    [{ name: 'onFiles', type: 'function', default: 'undefined' },
     { name: 'accept', type: 'string', default: 'undefined' },
     { name: 'multiple', type: 'boolean', default: 'false' },
     { name: 'label', type: 'ReactNode', default: 'undefined' },
     { name: 'sublabel', type: 'ReactNode', default: 'undefined' },
     { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' },
     { name: 'disabled', type: 'boolean', default: 'false' }],
    [{ state: 'Dragging over', setBy: 'interaction' },
     { state: 'Focus-visible', setBy: 'interaction' },
     { state: 'Disabled', setBy: 'prop' }],
    [surfaceToken('--Border', 'the dashed edge'), surfaceToken('--Hover', 'the drag-over fill')],
    ['Label and sublabel are props. It contains a real file input so the keyboard path works.'],
    ['Drag and drop is not keyboard-operable, so a DropZone must also be clickable and focusable — the hidden input is what provides that.',
     '`accept` should be stated in the sublabel too; a rejected file with no explanation is a dead end.'],
    ['No Figma drawing. It is a bordered region with an icon and two lines of text — build from `ImagePlaceholder` and `Card`.']),

  undesigned('StateMessage',
    'What to show when there is nothing to show: empty, error or no results.',
    [{ when: 'Something is loading', use: 'Loader or Skeleton' },
     { when: 'It is a transient message', use: 'Snackbar' },
     { when: 'It sits in the page as a warning', use: 'Alert' }],
    [{ name: 'type', type: 'string', values: ['empty', 'error', 'no-results'], default: 'empty' },
     { name: 'title', type: 'string', default: 'undefined' },
     { name: 'body', type: 'string', default: 'undefined' },
     { name: 'action', type: 'ReactNode', default: 'undefined', note: 'The way out. An empty state with no next step is a dead end.' },
     { name: 'icon', type: 'ReactNode', default: 'undefined' },
     { name: 'size', type: 'string', values: ['small', 'medium', 'large'], default: 'medium' }],
    [{ state: 'None', setBy: 'prop', note: 'The `type` IS the state.' }],
    [surfaceToken('--Text', 'the title'), surfaceToken('--Quiet', 'the body')],
    ['Title, body and action are props. Table and List take it through their own `empty` and `error` props.'],
    ['An error state must say what to do, not only what failed.',
     'It should be announced when it replaces content, or a screen reader user sees the list simply vanish.'],
    ['No Figma drawing. It is a centred icon, a title, a body and one action — build from Typography and Button.']),
];
