import { supabase } from './supabase/client';
import type { ColorScheme, UserSelections, TypographyStyle, ComponentStyle, SurfaceStyle } from '../types';
import { toneToColorNumber } from './colorScale';
import { generateFullLightPalettes, generateFullDarkPalettes } from './generateFullPalettes';
import { exportColorSystemToJSON } from './cssgen/exportColorSystem';
import { generateCSSFiles, generateBaseCSS } from './cssgen/exportToCSS';

const SUPABASE_STORAGE_BASE = `https://aqpmdqlhffjakkznxudv.supabase.co/storage/v1/object/public/design-system`;
const BUCKET = 'design-system';

const BORDER_RADII: Record<ComponentStyle, { small: number; medium: number; large: number }> = {
  professional: { small: 4, medium: 8, large: 12 },
  modern: { small: 6, medium: 12, large: 16 },
  bold: { small: 2, medium: 4, large: 8 },
  playful: { small: 12, medium: 20, large: 28 },
};

interface GenerateInput {
  designSystemName: string;
  colorScheme: ColorScheme;
  userSelections: UserSelections;
  typographyStyles: TypographyStyle[];
  componentStyle: ComponentStyle;
  surfaceStyle?: SurfaceStyle;
}

// ─── Map our button mode names to the pipeline's button style names ───
function mapButtonStyle(button: string): string {
  switch (button) {
    case 'primary': return 'primary-fixed';
    case 'secondary': return 'secondary-fixed';
    case 'tonal': return 'tonal-fixed';
    case 'laddered': return 'laddered-fixed';
    case 'black-white': return 'black-white';
    default: return 'primary-fixed';
  }
}

// ─── DINO-TOKENS.md ───
function buildDinoTokensMd(uuid: string, input: GenerateInput): string {
  const colors = input.colorScheme.colors;
  const radii = BORDER_RADII[input.componentStyle];
  const showcaseBase = 'https://sunny-cendol-af27ce.netlify.app';
  const storybookUrl = 'https://dinodesign.ai/storybook';

  return `# ${input.designSystemName} — Dino Design System

## Your Design System

| | |
|---|---|
| **Dino ID** | \`${uuid}\` |
| **Playground** | [${showcaseBase}/?user=${uuid}](${showcaseBase}/?user=${uuid}) |
| **Figma** | Open the Dino Figma plugin and paste your Dino ID |
| **Storybook** | [${storybookUrl}](${storybookUrl}) |

### Connect to Claude or Cursor

\`\`\`bash
npm install @dynodesign/components
npx @dynodesign/init ${uuid}
\`\`\`

---

## Brand Colors

\`\`\`css
:root {
  --color-primary: ${colors[0]};
  --color-secondary: ${colors[1]};
  --color-tertiary: ${colors[2]};
}
\`\`\`

## Available data-theme Values

### Light Themes
Default, Primary-Light, Primary, Secondary-Light, Secondary, Tertiary-Light, Tertiary, Neutral-Light, Neutral

### Dark Themes
Primary-Dark, Secondary-Dark, Tertiary-Dark, Neutral-Dark

### Semantic Themes
Error-Light, Success-Light, Warning-Light, Info-Light, Error-Dark, Success-Dark, Warning-Dark, Info-Dark

### Navigation Themes
App-Bar, Nav-Bar, Status

## data-style Values
Professional (${radii.small}px), Modern (${radii.medium}px), Bold, Playful

Selected: **${input.componentStyle}**

## data-surface Values
Surface, Surface-Dim, Surface-Bright, Container, Container-Low, Container-Lowest, Container-High

## Typography

| Role | Family | Weight |
|------|--------|--------|
${input.typographyStyles.map(t => `| ${t.type} | ${t.family} | ${t.weight} |`).join('\n')}

## DynoDesignProvider Setup

\`\`\`jsx
import { DynoDesignProvider } from '@dynodesign/components';

const SUPABASE_BASE = '${SUPABASE_STORAGE_BASE}/${uuid}';

function App() {
  return (
    <DynoDesignProvider
      themeURL={\`\${SUPABASE_BASE}\`}
      defaultTheme="Default"
      defaultStyle="${input.componentStyle.charAt(0).toUpperCase() + input.componentStyle.slice(1)}"
      defaultSurface="Surface"
    >
      {/* Your app */}
    </DynoDesignProvider>
  );
}
\`\`\`

## Token Reference

\`\`\`css
var(--Background)         /* page background */
var(--Text)               /* body text */
var(--Header)             /* heading text */
var(--Quiet)              /* muted text */
var(--Container)          /* card background */
var(--Border)             /* borders */
var(--Style-Border-Radius) /* border radius */
var(--Buttons-Primary-Button) /* button fill */
var(--Buttons-Primary-Text)   /* button label */
\`\`\`

## Components

Import from \`@dynodesign/components\`:

\`\`\`jsx
import {
  Button, Card, TextField, Alert, AppBar,
  H1, H2, H3, Body, BodySmall,
  VStack, HStack, Tabs, Dialog, Modal,
  // ... 49 components total
} from '@dynodesign/components';
\`\`\`

---

Generated by [Dino Design](https://dinodesign.ai)
`;
}

// ─── Main generation function ───

export async function generateAndUploadDesignSystem(input: GenerateInput): Promise<string> {
  const uuid = crypto.randomUUID();

  // 1. Build full 9-palette sets for light and dark mode
  const lightPalettes = input.colorScheme.tonePalettes || {};
  const darkPalettes = input.colorScheme.darkModeTonePalettes || {};

  const fullLightPalettes = generateFullLightPalettes(
    lightPalettes.primary || [],
    lightPalettes.secondary || [],
    lightPalettes.tertiary || [],
  );

  const fullDarkPalettes = generateFullDarkPalettes(
    darkPalettes.primary || [],
    darkPalettes.secondary || [],
    darkPalettes.tertiary || [],
  );

  // 2. Generate the complete JSON via the real pipeline
  const selectedBackground = input.userSelections.backgroundTheme === 'Primary' ? 'primary' as const : 'neutral' as const;
  const buttonStyle = mapButtonStyle(input.userSelections.button);

  const header = input.typographyStyles.find(t => t.type === 'header');
  const decorative = input.typographyStyles.find(t => t.type === 'decorative');
  const body = input.typographyStyles.find(t => t.type === 'body');

  let designSystemJSON: any;
  try {
    designSystemJSON = exportColorSystemToJSON(
      fullLightPalettes,
      fullDarkPalettes,
      selectedBackground,
      buttonStyle as any,
      input.colorScheme.extractedTones,
      input.componentStyle,
      {
        header: header ? { family: header.family, weight: header.weight } : undefined,
        decorative: decorative ? { family: decorative.family, weight: decorative.weight } : undefined,
        body: body ? { family: body.family, weight: body.weight } : undefined,
      },
      input.designSystemName,
      new Date().toISOString().split('T')[0],
      new Date().toISOString().split('T')[0],
      {
        appBar: input.userSelections.appBar,
        navBar: input.userSelections.navBar,
        toolBar: 'white',
      },
      input.surfaceStyle || 'light-tonal',
      undefined,
      {
        defaultTheme: input.userSelections.defaultTheme,
        background: input.userSelections.background as any,
        appBar: input.userSelections.appBar as any,
        navBar: input.userSelections.navBar as any,
        status: input.userSelections.status as any,
        button: mapButtonStyle(input.userSelections.button) as any,
        cardColoring: input.userSelections.cardColoring,
        textColoring: input.userSelections.textColoring,
      },
    );
  } catch (err) {
    console.error('JSON generation failed, using fallback:', err);
    // Fallback to simplified JSON
    designSystemJSON = {
      name: input.designSystemName,
      colors: input.colorScheme.colors,
      error: 'Full generation failed, simplified export',
    };
  }

  // 3. Generate CSS files from the JSON
  let cssFiles: Record<string, string> = {};
  try {
    cssFiles = generateCSSFiles(designSystemJSON);
  } catch (err) {
    console.error('CSS generation failed:', err);
  }

  // Also generate base.css
  let baseCSS = '';
  try {
    baseCSS = generateBaseCSS(designSystemJSON);
  } catch (err) {
    console.error('Base CSS generation failed:', err);
  }

  // 4. Build theme.json
  const themeJson = JSON.stringify({
    foundation: 'foundation.css',
    core: 'core.css',
    lightMode: 'Light-Mode.css',
    darkMode: 'Dark-Mode.css',
    base: 'base.css',
    styles: 'styles.css',
    defaultTheme: 'Default',
    defaultStyle: input.componentStyle.charAt(0).toUpperCase() + input.componentStyle.slice(1),
    defaultSurface: 'Surface',
    darkTheme: 'Neutral-Dark',
  }, null, 2);

  // 5. Build foundation.css and styles.css (simple static files)
  const foundationCSS = `:root {
  --Shadow-1: 0px 0px 0px 1px #eeeeee;
  --Shadow-2: 0px 0px 0px 0px rgba(0, 0, 0, 0.0);
  --Style-Border-Radius: ${BORDER_RADII[input.componentStyle].medium}px;
  --Style-Gradient-Color-1: var(--Buttons-Primary-Button);
  --Style-Gradient-Color-2: var(--Buttons-Primary-Button);
  --Style-Gradient-Angle: 0;
}
`;

  const coreCSS = `/* Core - Sizing */
:root {
  --Container-Padding: 24px;
  --Sizing-1: 8px;
  --Sizing-2: 16px;
  --Sizing-3: 24px;
  --Sizing-4: 32px;
  --Sizing-Half: 4px;
  --Sizing-Quarter: 2px;
  --Body-Font-Size: 16px;
  --Body-Line-Height: 24px;
  --H1-Font-Size: 40px;
  --H1-Line-Height: 40px;
  --H2-Font-Size: 32px;
  --H2-Line-Height: 40px;
  --H3-Font-Size: 28px;
  --H3-Line-Height: 36px;
  --Button-Font-Size: 16px;
  --Button-Line-Height: 20px;
  --Set-Font-Family-Header: '${header?.family || 'sans-serif'}', serif;
  --Set-Font-Family-Header-Weight: ${header?.weight || '700'};
  --Set-Font-Family-Decorative: '${decorative?.family || 'sans-serif'}', sans-serif;
  --Set-Font-Family-Body: '${body?.family || 'sans-serif'}', sans-serif;
  --Set-Font-Family-Body-Weight: ${body?.weight || '400'};
  --Set-Font-Family-Body-Semibold-Weight: 600;
  --Set-Font-Family-Body-Bold-Weight: 700;
}
`;

  const stylesCSS = `/* Overrides */\n`;

  // 6. Assemble all files for upload
  const uploadFiles: { name: string; content: string; type: string }[] = [
    { name: 'foundation.css', content: foundationCSS, type: 'text/css' },
    { name: 'core.css', content: coreCSS, type: 'text/css' },
    { name: 'styles.css', content: stylesCSS, type: 'text/css' },
    { name: 'theme.json', content: themeJson, type: 'application/json' },
    { name: 'tokens.json', content: JSON.stringify(designSystemJSON, null, 2), type: 'application/json' },
    { name: 'DINO-TOKENS.md', content: buildDinoTokensMd(uuid, input), type: 'text/markdown' },
  ];

  // Add generated CSS files (Light-Mode.css, Dark-Mode.css, etc.)
  if (cssFiles['Light-Mode.css']) {
    uploadFiles.push({ name: 'Light-Mode.css', content: cssFiles['Light-Mode.css'], type: 'text/css' });
  }
  if (cssFiles['Dark-Mode.css']) {
    uploadFiles.push({ name: 'Dark-Mode.css', content: cssFiles['Dark-Mode.css'], type: 'text/css' });
  }
  if (baseCSS) {
    uploadFiles.push({ name: 'base.css', content: baseCSS, type: 'text/css' });
  }

  // Add any other generated CSS files
  for (const [name, content] of Object.entries(cssFiles)) {
    if (name !== 'Light-Mode.css' && name !== 'Dark-Mode.css') {
      uploadFiles.push({ name, content, type: 'text/css' });
    }
  }

  // 7. Upload all files to Supabase Storage
  for (const file of uploadFiles) {
    const { error } = await supabase.storage
      .from(BUCKET)
      .upload(`${uuid}/${file.name}`, file.content, {
        contentType: file.type,
        upsert: true,
      });

    if (error) {
      console.error(`Failed to upload ${file.name}:`, error);
      throw new Error(`Upload failed for ${file.name}: ${error.message}`);
    }
  }

  console.log(`Design system uploaded: ${uuid}`);
  console.log(`Files: ${uploadFiles.map(f => f.name).join(', ')}`);
  return uuid;
}

export { SUPABASE_STORAGE_BASE };
