import { supabase } from './supabase/client';
import type { ColorScheme, UserSelections, TypographyStyle, ComponentStyle, SurfaceStyle } from '../types';
import { toneToColorNumber } from './colorScale';
import { generateFullLightPalettes, generateFullDarkPalettes } from './generateFullPalettes';
import { exportColorSystemToJSON } from './cssgen/exportColorSystem';
import { generateCSSFiles, generateBaseCSS } from './cssgen/exportToCSS';
import { generateFigmaJSON } from './generateFigmaJSON';

const SUPABASE_STORAGE_BASE = `https://aqpmdqlhffjakkznxudv.supabase.co/storage/v1/object/public/design-system`;
const BUCKET = 'design-system';

const BORDER_RADII: Record<ComponentStyle, { small: number; medium: number; large: number }> = {
  professional: { small: 4, medium: 8, large: 12 },
  modern: { small: 6, medium: 12, large: 16 },
  bold: { small: 2, medium: 4, large: 8 },
  playful: { small: 12, medium: 20, large: 28 },
};

interface GenerateInput {
  designSystemName: string;
  colorScheme: ColorScheme;
  userSelections: UserSelections;
  typographyStyles: TypographyStyle[];
  componentStyle: ComponentStyle;
  styleCustomizations?: any;
  surfaceStyle?: SurfaceStyle;
  moodBoardUrl?: string | null;
  moodBoardFile?: File | null;
}

// ─── Map our button mode names to the pipeline's button style names ───
function mapButtonStyle(button: string): string {
  switch (button) {
    case 'primary': return 'primary-fixed';
    case 'secondary': return 'secondary-fixed';
    case 'tonal': return 'tonal-fixed';
    case 'laddered': return 'laddered-fixed';
    case 'black-white': return 'black-white';
    default: return 'primary-fixed';
  }
}

// ─── DINO-TOKENS.md ───
function buildDinoTokensMd(uuid: string, input: GenerateInput): string {
  const colors = input.colorScheme.colors;
  const radii = BORDER_RADII[input.componentStyle];
  const showcaseBase = 'https://sunny-cendol-af27ce.netlify.app';
  const storybookUrl = `${showcaseBase}/storybook/?user=${uuid}`;

  return `# ${input.designSystemName} — Dino Design System

## Your Design System

| | |
|---|---|
| **Dino ID** | \`${uuid}\` |
| **Playground** | [${showcaseBase}/?user=${uuid}](${showcaseBase}/?user=${uuid}) |
| **Figma** | Open the Dino Figma plugin and paste your Dino ID |
| **Storybook** | [${storybookUrl}](${storybookUrl}) |

### Connect to Claude or Cursor

\`\`\`bash
npm install @dynodesign/components
npx @dynodesign/init ${uuid}
\`\`\`

---

## Brand Colors

\`\`\`css
:root {
  --color-primary: ${colors[0]};
  --color-secondary: ${colors[1]};
  --color-tertiary: ${colors[2]};
}
\`\`\`

## Available data-theme Values

### Light Themes
Default, Primary-Light, Primary, Secondary-Light, Secondary, Tertiary-Light, Tertiary, Neutral-Light, Neutral

### Dark Themes
Primary-Dark, Secondary-Dark, Tertiary-Dark, Neutral-Dark

### Semantic Themes
Error-Light, Success-Light, Warning-Light, Info-Light, Error-Dark, Success-Dark, Warning-Dark, Info-Dark

### Navigation Themes
App-Bar, Nav-Bar, Status

## data-style Values
Professional (${radii.small}px), Modern (${radii.medium}px), Bold, Playful

Selected: **${input.componentStyle}**

## data-surface Values
Surface, Surface-Dim, Surface-Bright, Container, Container-Low, Container-Lowest, Container-High

## Typography

| Role | Family | Weight |
|------|--------|--------|
${input.typographyStyles.map(t => `| ${t.type} | ${t.family} | ${t.weight} |`).join('\n')}

## DynoDesignProvider Setup

\`\`\`jsx
import { DynoDesignProvider } from '@dynodesign/components';

const SUPABASE_BASE = '${SUPABASE_STORAGE_BASE}/${uuid}';

function App() {
  return (
    <DynoDesignProvider
      themeURL={\`\${SUPABASE_BASE}\`}
      defaultTheme="Default"
      defaultStyle="${input.componentStyle.charAt(0).toUpperCase() + input.componentStyle.slice(1)}"
      defaultSurface="Surface"
    >
      {/* Your app */}
    </DynoDesignProvider>
  );
}
\`\`\`

## Token Reference

\`\`\`css
var(--Background)         /* page background */
var(--Text)               /* body text */
var(--Header)             /* heading text */
var(--Quiet)              /* muted text */
var(--Container)          /* card background */
var(--Border)             /* borders */
var(--Style-Border-Radius) /* border radius */
var(--Buttons-Primary-Button) /* button fill */
var(--Buttons-Primary-Text)   /* button label */
\`\`\`

## Components

Import from \`@dynodesign/components\`:

\`\`\`jsx
import {
  Button, Card, TextField, Alert, AppBar,
  H1, H2, H3, Body, BodySmall,
  VStack, HStack, Tabs, Dialog, Modal,
  // ... 49 components total
} from '@dynodesign/components';
\`\`\`

---

Generated by [Dino Design](https://dinodesign.ai)
`;
}

// ─── Main generation function ───

export async function generateAndUploadDesignSystem(input: GenerateInput): Promise<string> {
  const uuid = crypto.randomUUID();

  // 1. Build full 9-palette sets for light and dark mode
  const lightPalettes = input.colorScheme.tonePalettes || {};
  const darkPalettes = input.colorScheme.darkModeTonePalettes || {};

  const fullLightPalettes = generateFullLightPalettes(
    lightPalettes.primary || [],
    lightPalettes.secondary || [],
    lightPalettes.tertiary || [],
  );

  const fullDarkPalettes = generateFullDarkPalettes(
    darkPalettes.primary || [],
    darkPalettes.secondary || [],
    darkPalettes.tertiary || [],
  );

  // 2. Generate the complete JSON via the real pipeline
  const selectedBackground = input.userSelections.backgroundTheme === 'Primary' ? 'primary' as const : 'neutral' as const;
  const buttonStyle = mapButtonStyle(input.userSelections.button);

  const header = input.typographyStyles.find(t => t.type === 'header');
  const decorative = input.typographyStyles.find(t => t.type === 'decorative');
  const body = input.typographyStyles.find(t => t.type === 'body');

  let designSystemJSON: any;
  try {
    designSystemJSON = exportColorSystemToJSON(
      fullLightPalettes,
      fullDarkPalettes,
      selectedBackground,
      buttonStyle as any,
      input.colorScheme.extractedTones,
      input.componentStyle,
      {
        header: header ? { family: header.family, weight: header.weight } : undefined,
        decorative: decorative ? { family: decorative.family, weight: decorative.weight } : undefined,
        body: body ? { family: body.family, weight: body.weight } : undefined,
      },
      input.designSystemName,
      new Date().toISOString().split('T')[0],
      new Date().toISOString().split('T')[0],
      {
        appBar: input.userSelections.appBar,
        navBar: input.userSelections.navBar,
        toolBar: 'white',
      },
      input.surfaceStyle || 'light-tonal',
      undefined,
      {
        defaultTheme: input.userSelections.defaultTheme,
        background: input.userSelections.background as any,
        appBar: input.userSelections.appBar as any,
        navBar: input.userSelections.navBar as any,
        status: input.userSelections.status as any,
        button: mapButtonStyle(input.userSelections.button) as any,
        cardColoring: input.userSelections.cardColoring,
        textColoring: input.userSelections.textColoring,
      },
    );

    // Add Platform section to JSON
    designSystemJSON.Platform = {
      Desktop: {
        'Container-Padding': { value: 'var(--Sizing-4)', type: 'spacing' },
        'Button-Height': { value: '32px', type: 'sizing' },
        'Min-Button-Width': { value: '80px', type: 'sizing' },
        'Min-Stack-Gap': { value: '0px', type: 'spacing' },
        'Platform-Label': { value: 'Desktop', type: 'string' },
      },
      'IOS-Mobile': {
        'Container-Padding': { value: 'var(--Sizing-2)', type: 'spacing' },
        'Button-Height': { value: '44px', type: 'sizing' },
        'Min-Stack-Gap': { value: '10px', type: 'spacing' },
        'Platform-Label': { value: 'IOS-Mobile', type: 'string' },
      },
      'IOS-Tablet': {
        'Container-Padding': { value: 'var(--Sizing-3)', type: 'spacing' },
        'Button-Height': { value: '48px', type: 'sizing' },
        'Min-Stack-Gap': { value: '10px', type: 'spacing' },
        'Platform-Label': { value: 'IOS-Tablet', type: 'string' },
      },
      Android: {
        'Container-Padding': { value: 'var(--Sizing-2)', type: 'spacing' },
        'Button-Height': { value: '48px', type: 'sizing' },
        'Min-Stack-Gap': { value: '12px', type: 'spacing' },
        'Platform-Label': { value: 'Android', type: 'string' },
      },
    };

    // Add Cognitive Accessibility section to JSON
    designSystemJSON.Cognitive = {
      Dyslexia: {
        'Cognitive-Multiplier': { value: '1.5', type: 'number' },
        'Body-Font-Family': { value: 'OpenDyslexic', type: 'fontFamily' },
      },
      ADHD: {
        'Cognitive-Multiplier': { value: '1.5', type: 'number' },
      },
    };
  } catch (err) {
    console.error('JSON generation failed, using fallback:', err);
    // Fallback to simplified JSON
    designSystemJSON = {
      name: input.designSystemName,
      colors: input.colorScheme.colors,
      error: 'Full generation failed, simplified export',
    };
  }

  // 3. Generate CSS files from the JSON
  let cssFiles: Record<string, string> = {};
  cssFiles = generateCSSFiles(designSystemJSON);
  console.log('✅ CSS files generated:', Object.keys(cssFiles));

  // Also generate base.css
  let baseCSS = '';
  try {
    baseCSS = generateBaseCSS(designSystemJSON);
  } catch (err) {
    console.error('Base CSS generation failed:', err);
  }

  // 4. Build theme.json
  const themeJson = JSON.stringify({
    foundation: 'foundation.css',
    core: 'core.css',
    lightMode: 'Light-Mode.css',
    darkMode: 'Dark-Mode.css',
    base: 'base.css',
    styles: 'styles.css',
    defaultTheme: 'Default',
    defaultStyle: input.componentStyle.charAt(0).toUpperCase() + input.componentStyle.slice(1),
    defaultSurface: 'Surface',
    darkTheme: 'Neutral-Dark',
  }, null, 2);

  // 5. Build foundation.css and styles.css (simple static files)
  const headerFamily = header?.family || 'sans-serif';
  const decorativeFamily = decorative?.family || 'sans-serif';
  const bodyFamily = body?.family || 'sans-serif';
  const headerWeight = header?.weight || '700';
  const bodyWeight = body?.weight || '400';
  // Get customizations from input, fallback to preset defaults
  const sc = input.styleCustomizations;
  const buttonRadius = sc?.buttonRadius ?? BORDER_RADII[input.componentStyle].medium;
  const cardRadius = sc?.radius ?? Math.round(buttonRadius * 1.33);
  const cardPadding = cardRadius >= 16 ? 20 : 16;
  const buttonHeight = sc?.buttonHeight ?? 36;
  const smallButtonHeight = sc?.smallButtonHeight ?? 24;
  const largeButtonHeight = sc?.largeButtonHeight ?? 56;
  const minButtonWidth = sc?.minButtonWidth ?? 60;
  const iconButtonRadius = sc?.iconButtonRadius ?? buttonRadius;
  const bevelPercent = sc?.bevel ?? 0;
  const bevelOpacity = sc?.bevelOpacity ?? 50;
  const bevelPx = Math.round(buttonHeight * bevelPercent / 100);

  const foundationCSS = `:root {

  /* Button */
  --Button-Radius: ${buttonRadius}px;
  --Button-Icon-Radius: ${iconButtonRadius}px;
  --Button-Height: ${buttonHeight}px;
  --Small-Button-Height: ${smallButtonHeight}px;
  --Large-Button-Height: ${largeButtonHeight}px;
  --Button-Min-Width: ${minButtonWidth}px;
  --Button-Bevel: ${bevelPercent}%;
  --Button-Bevel-Px: ${bevelPx}px;
  --Button-Bevel-Opacity: ${bevelOpacity}%;
  --Button-Bevel-Shadow: ${bevelPx > 0 ? `inset -${bevelPx}px -${bevelPx}px ${bevelPx}px color-mix(in srgb, var(--Buttons-Default-Highlight, #ffffff) ${bevelOpacity}%, transparent), inset ${bevelPx}px ${bevelPx}px ${bevelPx}px color-mix(in srgb, var(--Buttons-Default-Lowlight, #000000) ${bevelOpacity}%, transparent)` : 'none'};
  --Style-Border-Radius: var(--Button-Radius);

  /* Card */
  --Card-Radius: ${cardRadius}px;
  --Card-Focus-Radius: ${cardRadius + 3}px;
  --Card-Padding: ${cardPadding}px;
  --Style-Gradient-Color-1: var(--Buttons-Primary-Button);
  --Style-Gradient-Color-2: var(--Buttons-Primary-Button);
  --Style-Gradient-Angle: 0;

  --Sizing-1: 8px;
  --Sizing-2: 16px;
  --Sizing-3: 24px;
  --Sizing-4: 32px;
  --Sizing-Half: 4px;
  --Sizing-Quarter: 2px;
  --Sizing-Negative-1: -8px;
  --Sizing-Negative-Half: -4px;
  --Sizing-Negative-Quarter: -2px;
  --Sizing-Negative-1-and-Half: -12px;
  --Min-Stack-Gap: 0px;
}
`;

  const coreCSS = `:root {
  --Body-Font-Family: var(--Set-Font-Family-Body);
  --Font-Family-Body: var(--Set-Font-Family-Body);
  --Header-Font-Family: var(--Set-Font-Family-Header);
  --Font-Family-Header: var(--Set-Font-Family-Header);
  --Header-Font-Weight: var(--Set-Font-Family-Header-Weight);
  --Decorative-Font-Family: var(--Set-Font-Family-Decorative);
  --Decorative-Font-Weight: var(--Set-Font-Family-Decorative-Weight);
  --Body-Font-Weight: var(--Set-Font-Family-Body-Weight);
  --Body-Semibold-Font-Weight: var(--Set-Font-Family-Body-Semibold-Weight);
  --Body-Bold-Font-Weight: var(--Set-Font-Family-Body-Bold-Weight);
  --Cognitive-Multiplier: 1;
}

/* Platform Font Overrides */
[data-platform="IOS-Mobile"][data-fonts] {
  --Body-Font-Family: var(--Set-Font-Family-Body);
  --Header-Font-Family: var(--Set-Font-Family-Header);
  --Header-Font-Weight: var(--Set-Font-Family-Header-Weight);
  --Decorative-Font-Family: var(--Set-Font-Family-Decorative);
  --Decorative-Font-Weight: var(--Set-Font-Family-Decorative-Weight);
  --Body-Font-Weight: var(--Set-Font-Family-Body-Weight);
  --Body-Semibold-Font-Weight: var(--Set-Font-Family-Body-Semibold-Weight);
  --Body-Bold-Font-Weight: var(--Set-Font-Family-Body-Bold-Weight);
}
[data-platform="IOS-Tablet"][data-fonts] {
  --Body-Font-Family: var(--Set-Font-Family-Body);
  --Header-Font-Family: var(--Set-Font-Family-Header);
  --Header-Font-Weight: var(--Set-Font-Family-Header-Weight);
  --Decorative-Font-Family: var(--Set-Font-Family-Decorative);
  --Decorative-Font-Weight: var(--Set-Font-Family-Decorative-Weight);
  --Body-Font-Weight: var(--Set-Font-Family-Body-Weight);
  --Body-Semibold-Font-Weight: var(--Set-Font-Family-Body-Semibold-Weight);
  --Body-Bold-Font-Weight: var(--Set-Font-Family-Body-Bold-Weight);
}
[data-platform="Android"][data-fonts] {
  --Body-Font-Family: var(--Set-Font-Family-Body);
  --Header-Font-Family: var(--Set-Font-Family-Header);
  --Header-Font-Weight: var(--Set-Font-Family-Header-Weight);
  --Decorative-Font-Family: var(--Set-Font-Family-Decorative);
  --Decorative-Font-Weight: var(--Set-Font-Family-Decorative-Weight);
  --Body-Font-Weight: var(--Set-Font-Family-Body-Weight);
  --Body-Semibold-Font-Weight: var(--Set-Font-Family-Body-Semibold-Weight);
  --Body-Bold-Font-Weight: var(--Set-Font-Family-Body-Bold-Weight);
}

[data-platform="IOS-Mobile"][data-fonts="Default"] {
  --Body-Font-Family: "SF Pro";
  --Header-Font-Family: "SF Pro";
  --Header-Font-Weight: var(--Set-Font-Family-Header-Weight);
  --Decorative-Font-Family: "SF Pro";
  --Decorative-Font-Weight: var(--Set-Font-Family-Decorative-Weight);
  --Body-Font-Weight: var(--Set-Font-Family-Body-Weight);
  --Body-Semibold-Font-Weight: var(--Set-Font-Family-Body-Semibold-Weight);
  --Body-Bold-Font-Weight: var(--Set-Font-Family-Body-Bold-Weight);
}
[data-platform="IOS-Tablet"][data-fonts="Default"] {
  --Body-Font-Family: "SF Pro";
  --Header-Font-Family: "SF Pro";
  --Header-Font-Weight: var(--Set-Font-Family-Header-Weight);
  --Decorative-Font-Family: "SF Pro";
  --Decorative-Font-Weight: var(--Set-Font-Family-Decorative-Weight);
  --Body-Font-Weight: var(--Set-Font-Family-Body-Weight);
  --Body-Semibold-Font-Weight: var(--Set-Font-Family-Body-Semibold-Weight);
  --Body-Bold-Font-Weight: var(--Set-Font-Family-Body-Bold-Weight);
}
[data-platform="Android"][data-fonts="Default"] {
  --Body-Font-Family: "Roboto";
  --Header-Font-Family: "Roboto";
  --Header-Font-Weight: var(--Set-Font-Family-Header-Weight);
  --Decorative-Font-Family: "Roboto";
  --Decorative-Font-Weight: var(--Set-Font-Family-Decorative-Weight);
  --Body-Font-Weight: var(--Set-Font-Family-Body-Weight);
  --Body-Semibold-Font-Weight: var(--Set-Font-Family-Body-Semibold-Weight);
  --Body-Bold-Font-Weight: var(--Set-Font-Family-Body-Bold-Weight);
}

/* Desktop Defaults */
:root {
  --Container-Padding: var(--Sizing-4);
  --Platform-Label: "Desktop";
  --Button-Height: 32px;
  --Min-Button-Width: 80px;
  --Set-Font-Family-Header: '${headerFamily}', serif;
  --Set-Font-Family-Header-Weight: ${headerWeight};
  --Set-Font-Family-Decorative: '${decorativeFamily}', sans-serif;
  --Set-Font-Family-Body: '${bodyFamily}', sans-serif;
  --Set-Font-Family-Body-Weight: ${bodyWeight};
  --Set-Font-Family-Body-Semibold-Weight: 600;
  --Set-Font-Family-Body-Bold-Weight: 700;
  --Body-Font-Size: 16px;
  --Body-Letter-Spacing: 0;
  --Body-Line-Height: 24px;
  --Body-Paragraph-Spacing: 16px;
  --H1-Font-Size: 40px;
  --H1-Line-Height: 40px;
  --H1-Letter-Spacing: -1px;
  --H1-Paragraph-Spacing: 32px;
  --H2-Font-Size: 32px;
  --H2-Line-Height: 40px;
  --H2-Letter-Spacing: -1px;
  --H2-Paragraph-Spacing: 24px;
  --H3-Font-Size: 28px;
  --H3-Line-Height: 36px;
  --H3-Letter-Spacing: -.5px;
  --H3-Paragraph-Spacing: 20px;
  --H4-Font-Size: 24px;
  --H4-Line-Height: 32px;
  --H4-Letter-Spacing: -.5px;
  --H4-Paragraph-Spacing: 16px;
  --H5-Font-Size: 20px;
  --H5-Line-Height: 28px;
  --H5-Letter-Spacing: 0px;
  --H5-Paragraph-Spacing: 12px;
  --H6-Font-Size: 18px;
  --H6-Line-Height: 26px;
  --H6-Letter-Spacing: 0px;
  --H6-Paragraph-Spacing: 12px;
  --Label-Font-Size: 14px;
  --Label-Line-Height: 20px;
  --Label-Letter-Spacing: 0px;
  --Label-Paragraph-Spacing: 4px;
  --Button-Font-Size: 16px;
  --Button-Line-Height: 20px;
}

/* iOS Mobile */
[data-platform="IOS-Mobile"] {
  --Container-Padding: var(--Sizing-2);
  --Platform-Label: "IOS-Mobile";
  --Button-Height: 44px;
  --Min-Stack-Gap: 10px;
  --Body-Font-Size: 16px;
  --Body-Letter-Spacing: -.5px;
  --Body-Line-Height: 24px;
  --Body-Paragraph-Spacing: 16px;
  --H1-Font-Size: 32px;
  --H1-Line-Height: 40px;
  --H1-Letter-Spacing: -1px;
  --H1-Paragraph-Spacing: 24px;
  --H2-Font-Size: 28px;
  --H2-Line-Height: 32px;
  --H2-Letter-Spacing: -.5px;
  --H2-Paragraph-Spacing: 20px;
  --H3-Font-Size: 24px;
  --H3-Line-Height: 32px;
  --H3-Letter-Spacing: -.5px;
  --H3-Paragraph-Spacing: 16px;
  --H4-Font-Size: 20px;
  --H4-Line-Height: 28px;
  --H4-Letter-Spacing: 0px;
  --H4-Paragraph-Spacing: 12px;
  --H5-Font-Size: 18px;
  --H5-Line-Height: 26px;
  --H5-Letter-Spacing: 0px;
  --H5-Paragraph-Spacing: 12px;
  --H6-Font-Size: 16px;
  --H6-Line-Height: 24px;
  --H6-Letter-Spacing: .5px;
  --H6-Paragraph-Spacing: 8px;
  --Label-Font-Size: 13px;
  --Label-Line-Height: 18px;
  --Label-Letter-Spacing: 0px;
  --Label-Paragraph-Spacing: 4px;
  --Button-Font-Size: 16px;
  --Button-Line-Height: 20px;
}

/* iOS Tablet */
[data-platform="IOS-Tablet"] {
  --Container-Padding: var(--Sizing-3);
  --Platform-Label: "IOS-Tablet";
  --Button-Height: 48px;
  --Min-Stack-Gap: 10px;
  --Body-Font-Size: 17px;
  --Body-Letter-Spacing: -.5px;
  --Body-Line-Height: 25.5px;
  --Body-Paragraph-Spacing: 16px;
  --H1-Font-Size: 40px;
  --H1-Line-Height: 48px;
  --H1-Letter-Spacing: -1.5px;
  --H1-Paragraph-Spacing: 32px;
  --H2-Font-Size: 32px;
  --H2-Line-Height: 40px;
  --H2-Letter-Spacing: -1px;
  --H2-Paragraph-Spacing: 24px;
  --H3-Font-Size: 28px;
  --H3-Line-Height: 36px;
  --H3-Letter-Spacing: -.5px;
  --H3-Paragraph-Spacing: 20px;
  --H4-Font-Size: 24px;
  --H4-Line-Height: 32px;
  --H4-Letter-Spacing: -.5px;
  --H4-Paragraph-Spacing: 16px;
  --H5-Font-Size: 20px;
  --H5-Line-Height: 28px;
  --H5-Letter-Spacing: 0px;
  --H5-Paragraph-Spacing: 12px;
  --H6-Font-Size: 18px;
  --H6-Line-Height: 26px;
  --H6-Letter-Spacing: 0px;
  --H6-Paragraph-Spacing: 12px;
  --Label-Font-Size: 14px;
  --Label-Line-Height: 20px;
  --Label-Letter-Spacing: 0px;
  --Label-Paragraph-Spacing: 4px;
  --Button-Font-Size: 17px;
  --Button-Line-Height: 21px;
}

/* Android */
[data-platform="Android"] {
  --Container-Padding: var(--Sizing-2);
  --Platform-Label: "Android";
  --Button-Height: 48px;
  --Min-Stack-Gap: 12px;
  --Body-Font-Size: 16px;
  --Body-Line-Height: 24px;
  --Body-Letter-Spacing: .5px;
  --Body-Paragraph-Spacing: 16px;
  --H1-Font-Size: 36px;
  --H1-Line-Height: 40px;
  --H1-Letter-Spacing: -.5px;
  --H1-Paragraph-Spacing: 20px;
  --H2-Font-Size: 28px;
  --H2-Line-Height: 36px;
  --H2-Letter-Spacing: -.5px;
  --H2-Paragraph-Spacing: 20px;
  --H3-Font-Size: 24px;
  --H3-Line-Height: 32px;
  --H3-Letter-Spacing: 0px;
  --H3-Paragraph-Spacing: 16px;
  --H4-Font-Size: 20px;
  --H4-Line-Height: 28px;
  --H4-Letter-Spacing: 0px;
  --H4-Paragraph-Spacing: 12px;
  --H5-Font-Size: 18px;
  --H5-Line-Height: 26px;
  --H5-Letter-Spacing: 0px;
  --H5-Paragraph-Spacing: 12px;
  --H6-Font-Size: 16px;
  --H6-Line-Height: 24px;
  --H6-Letter-Spacing: .5px;
  --H6-Paragraph-Spacing: 8px;
  --Label-Font-Size: 13px;
  --Label-Line-Height: 18px;
  --Label-Letter-Spacing: 0px;
  --Label-Paragraph-Spacing: 4px;
  --Button-Font-Size: 16px;
  --Button-Line-Height: 20px;
}

/* Decorative Font Application */
/* Typography variants: Header uses body font by default, Decorative Header uses decorative font */

[data-surface="Surface"] [data-decorative],
[data-surface="Surface-Dim"] [data-decorative],
[data-surface="Surface-Dimmest"] [data-decorative],
[data-surface="Surface-Bright"] [data-decorative] {
  --Font-Family-Header: var(--Set-Font-Family-Header);
  --Font-Family-Header-Weight: var(--Set-Font-Family-Header-Weight);
  --Font-Family-Overline: var(--Set-Font-Family-Decorative);
}

/* Explicit decorative variants — always available regardless of mode */
[data-typography="decorative-header"] {
  font-family: var(--Set-Font-Family-Header);
  font-weight: var(--Set-Font-Family-Header-Weight);
}
[data-typography="decorative-overline"] {
  font-family: var(--Set-Font-Family-Decorative);
}

/* Cognitive Accessibility Overrides */
[data-cognitive="Dyslexia"] {
  --Cognitive-Multiplier: 1.5;
  --Body-Font-Family: "OpenDyslexic";
  --Body-Font-Weight: 400;
  --Body-Semibold-Font-Weight: 700;
  --Body-Bold-Font-Weight: 700;
}

[data-cognitive="ADHD"] {
  --Cognitive-Multiplier: 1.5;
}
`;

  const stylesCSS = `/* Overrides */\n`;

  // 6. Import typography-tokens.css
  const { typographyTokensCSS } = await import('./typographyTokens');

  // 7. Assemble all files for upload
  const uploadFiles: { name: string; content: string; type: string }[] = [
    { name: 'foundation.css', content: foundationCSS, type: 'text/css' },
    { name: 'core.css', content: coreCSS, type: 'text/css' },
    { name: 'typography-tokens.css', content: typographyTokensCSS, type: 'text/css' },
    { name: 'styles.css', content: stylesCSS, type: 'text/css' },
    { name: 'theme.json', content: themeJson, type: 'application/json' },
    { name: 'tokens.json', content: JSON.stringify(designSystemJSON, null, 2), type: 'application/json' },
    { name: 'figma.json', content: (() => { try { if (input.styleCustomizations) designSystemJSON._componentStyle = input.styleCustomizations; designSystemJSON._userSelections = input.userSelections; return JSON.stringify(generateFigmaJSON(designSystemJSON), null, 2); } catch (e) { console.error('❌ figma.json generation failed:', e); return '{}'; } })(), type: 'application/json' },
    { name: 'DINO-TOKENS.md', content: buildDinoTokensMd(uuid, input), type: 'text/markdown' },
  ];

  // Add generated CSS files (Light-Mode.css, Dark-Mode.css, etc.)
  if (cssFiles['Light-Mode.css']) {
    uploadFiles.push({ name: 'Light-Mode.css', content: cssFiles['Light-Mode.css'], type: 'text/css' });
  }
  if (cssFiles['Dark-Mode.css']) {
    uploadFiles.push({ name: 'Dark-Mode.css', content: cssFiles['Dark-Mode.css'], type: 'text/css' });
  }
  if (baseCSS) {
    uploadFiles.push({ name: 'base.css', content: baseCSS, type: 'text/css' });
  }

  // Add any other generated CSS files
  for (const [name, content] of Object.entries(cssFiles)) {
    if (name !== 'Light-Mode.css' && name !== 'Dark-Mode.css') {
      uploadFiles.push({ name, content, type: 'text/css' });
    }
  }

  // 7. Upload mood board image if available
  const moodBoardSource = input.moodBoardFile || input.moodBoardUrl;
  if (moodBoardSource) {
    try {
      let blob: Blob;
      if (input.moodBoardFile) {
        blob = input.moodBoardFile;
      } else {
        const response = await fetch(input.moodBoardUrl!);
        blob = await response.blob();
      }
      const { error } = await supabase.storage
        .from(BUCKET)
        .upload(`${uuid}/moodboard.png`, blob, {
          contentType: blob.type || 'image/png',
          upsert: true,
        });
      if (error) console.error('Mood board upload failed:', error);
      else console.log(`Mood board uploaded (${(blob.size / 1024).toFixed(0)}KB)`);
    } catch (e) {
      console.error('Mood board upload error:', e);
    }
  }

  // 8. Upload all files to Supabase Storage
  for (const file of uploadFiles) {
    const { error } = await supabase.storage
      .from(BUCKET)
      .upload(`${uuid}/${file.name}`, file.content, {
        contentType: file.type,
        upsert: true,
      });

    if (error) {
      console.error(`Failed to upload ${file.name}:`, error);
      throw new Error(`Upload failed for ${file.name}: ${error.message}`);
    }
  }

  console.log(`Design system uploaded: ${uuid}`);
  console.log(`Files: ${uploadFiles.map(f => f.name).join(', ')}`);
  return uuid;
}

export { SUPABASE_STORAGE_BASE };
