/**
 * Fixed Border structure for Dark-Mode
 * This structure is constant and does not change based on color extraction
 */
export const darkModeBorderFixed = {
  Surfaces: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Neutral.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Neutral.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Neutral.Color-6}', type: 'color' as const }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Primary.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Primary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Primary.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Primary.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Primary.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Primary.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Primary.Color-6}', type: 'color' as const }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Secondary.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Secondary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Secondary.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Secondary.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Secondary.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Secondary.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Secondary.Color-6}', type: 'color' as const }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Tertiary.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Tertiary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Tertiary.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Tertiary.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Tertiary.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Tertiary.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Tertiary.Color-6}', type: 'color' as const }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Info.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Info.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Info.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Info.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Info.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Info.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Info.Color-6}', type: 'color' as const }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Success.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Success.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Success.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Success.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Success.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Success.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Success.Color-6}', type: 'color' as const }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Warning.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Warning.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Warning.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Warning.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Warning.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Warning.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Warning.Color-6}', type: 'color' as const }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Error.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Error.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Error.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Error.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Error.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Error.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Error.Color-6}', type: 'color' as const }
    }
  },
  Containers: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Neutral.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Neutral.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Neutral.Color-6}', type: 'color' as const }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Primary.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Primary.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Primary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Primary.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Primary.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Primary.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Primary.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Primary.Color-6}', type: 'color' as const }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Secondary.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Secondary.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Secondary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Secondary.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Secondary.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Secondary.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Secondary.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Secondary.Color-6}', type: 'color' as const }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Tertiary.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Tertiary.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Tertiary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Tertiary.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Tertiary.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Tertiary.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Tertiary.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Tertiary.Color-6}', type: 'color' as const }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Info.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Info.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Info.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Info.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Info.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Info.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Info.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Info.Color-6}', type: 'color' as const }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Success.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Success.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Success.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Success.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Success.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Success.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Success.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Success.Color-6}', type: 'color' as const }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Warning.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Warning.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Warning.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Warning.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Warning.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Warning.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Warning.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Warning.Color-6}', type: 'color' as const }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-2': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-3': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-4': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-5': { value: '{Colors.Error.Color-8}', type: 'color' as const },
      'Color-6': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-7': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-8': { value: '{Colors.Error.Color-10}', type: 'color' as const },
      'Color-9': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Error.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Error.Color-6}', type: 'color' as const },
      'Color-12': { value: '{Colors.Error.Color-7}', type: 'color' as const },
      'Color-13': { value: '{Colors.Error.Color-7}', type: 'color' as const },
      'Color-14': { value: '{Colors.Error.Color-7}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Error.Color-6}', type: 'color' as const }
    }
  }
};