/**
 * Fixed Header structure for Dark-Mode
 * Header uses references to Colors for all palettes
 * Dark Mode has different mappings than Light Mode
 */

export const darkModeHeaderFixed = {
  Surfaces: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Neutral.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Neutral.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Neutral.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Neutral.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Neutral.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Neutral.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Neutral.Color-11}', type: 'color' }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Primary.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Primary.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Primary.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Primary.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Primary.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Primary.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Primary.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Primary.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Primary.Color-11}', type: 'color' }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Secondary.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Secondary.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Secondary.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Secondary.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Secondary.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Secondary.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Secondary.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Secondary.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Secondary.Color-11}', type: 'color' }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Tertiary.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Tertiary.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Tertiary.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Tertiary.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Tertiary.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Tertiary.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Tertiary.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Tertiary.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Tertiary.Color-11}', type: 'color' }
    },
    BW: {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Colors.Neutral.Color-1}', type: 'color' }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Info.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Info.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Info.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Info.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Info.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Info.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Info.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Info.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Info.Color-11}', type: 'color' }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Success.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Success.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Success.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Success.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Success.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Success.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Success.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Success.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Success.Color-11}', type: 'color' }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Warning.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Warning.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Warning.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Warning.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Warning.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Warning.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Warning.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Warning.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Warning.Color-11}', type: 'color' }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Error.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Error.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Error.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Error.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Error.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Error.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Error.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Error.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Error.Color-11}', type: 'color' }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Hotlink-Visited.Color-11}', type: 'color' }
    }
  },
  Containers: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Neutral.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Neutral.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Neutral.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Neutral.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Neutral.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Neutral.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Neutral.Color-11}', type: 'color' }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Primary.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Primary.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Primary.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Primary.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Primary.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Primary.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Primary.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Primary.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Primary.Color-11}', type: 'color' }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Secondary.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Secondary.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Secondary.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Secondary.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Secondary.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Secondary.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Secondary.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Secondary.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Secondary.Color-11}', type: 'color' }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Tertiary.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Tertiary.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Tertiary.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Tertiary.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Tertiary.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Tertiary.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Tertiary.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Tertiary.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Tertiary.Color-11}', type: 'color' }
    },
    BW: {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Colors.Neutral.Color-1}', type: 'color' }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Info.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Info.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Info.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Info.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Info.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Info.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Info.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Info.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Info.Color-11}', type: 'color' }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Success.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Success.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Success.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Success.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Success.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Success.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Success.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Success.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Success.Color-11}', type: 'color' }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Warning.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Warning.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Warning.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Warning.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Warning.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Warning.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Warning.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Warning.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Warning.Color-11}', type: 'color' }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Error.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Error.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Error.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Error.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Error.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Error.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Error.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Error.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Error.Color-11}', type: 'color' }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-12}', type: 'color' },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-13}', type: 'color' },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-6}', type: 'color' },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-13': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-14': { value: '{Colors.Hotlink-Visited.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Modes.Light-Mode.Colors.Hotlink-Visited.Color-11}', type: 'color' }
    }
  }
};