/**
 * Fixed Text structure for Dark-Mode with Surfaces/Containers hierarchy
 * This structure is constant and does not change based on color extraction
 * Dark Mode has different mappings than Light Mode
 */
export const darkModeTextFixed = {
  Surfaces: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Neutral.Color-5}', type: 'color' as const }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Primary.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Primary.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Primary.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Primary.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Primary.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Primary.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Primary.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Primary.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Primary.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Primary.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Primary.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Primary.Color-5}', type: 'color' as const }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Secondary.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Secondary.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Secondary.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Secondary.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Secondary.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Secondary.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Secondary.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Secondary.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Secondary.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Secondary.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Secondary.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Secondary.Color-5}', type: 'color' as const }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Tertiary.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Tertiary.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Tertiary.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Tertiary.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Tertiary.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Tertiary.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Tertiary.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Tertiary.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Tertiary.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Tertiary.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Tertiary.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Tertiary.Color-5}', type: 'color' as const }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Info.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Info.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Info.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Info.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Info.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Info.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Info.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Info.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Info.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Info.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Info.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Info.Color-5}', type: 'color' as const }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Success.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Success.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Success.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Success.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Success.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Success.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Success.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Success.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Success.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Success.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Success.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Success.Color-5}', type: 'color' as const }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Warning.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Warning.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Warning.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Warning.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Warning.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Warning.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Warning.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Warning.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Warning.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Warning.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Warning.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Warning.Color-5}', type: 'color' as const }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Error.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Error.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Error.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Error.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Error.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Error.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Error.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Error.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Error.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Error.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Error.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Error.Color-5}', type: 'color' as const }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-13}', type: 'color' as const },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' as const },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-14}', type: 'color' as const },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-2}', type: 'color' as const },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-2}', type: 'color' as const },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' as const },
      'Color-13': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' as const }
    }
  },
  Containers: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Neutral.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Neutral.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Neutral.Color-11}', type: 'color' as const }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Primary.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Primary.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Primary.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Primary.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Primary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Primary.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Primary.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Primary.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Primary.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Primary.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Primary.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Primary.Color-11}', type: 'color' as const }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Secondary.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Secondary.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Secondary.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Secondary.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Secondary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Secondary.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Secondary.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Secondary.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Secondary.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Secondary.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Secondary.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Secondary.Color-11}', type: 'color' as const }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Tertiary.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Tertiary.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Tertiary.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Tertiary.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Tertiary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Tertiary.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Tertiary.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Tertiary.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Tertiary.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Tertiary.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Tertiary.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Tertiary.Color-11}', type: 'color' as const }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Info.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Info.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Info.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Info.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Info.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Info.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Info.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Info.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Info.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Info.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Info.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Info.Color-11}', type: 'color' as const }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Success.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Success.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Success.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Success.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Success.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Success.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Success.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Success.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Success.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Success.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Success.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Success.Color-11}', type: 'color' as const }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Warning.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Warning.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Warning.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Warning.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Warning.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Warning.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Warning.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Warning.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Warning.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Warning.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Warning.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Warning.Color-11}', type: 'color' as const }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Error.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Error.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Error.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Error.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Error.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Error.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Error.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Error.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Error.Color-5}', type: 'color' as const },
      'Color-13': { value: '{Colors.Error.Color-6}', type: 'color' as const },
      'Color-14': { value: '{Colors.Error.Color-6}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Error.Color-11}', type: 'color' as const }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' as const },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' as const },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-12}', type: 'color' as const },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' as const },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-12}', type: 'color' as const },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' as const },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-13': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-14': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Hotlink-Visited.Color-11}', type: 'color' as const }
    }
  }
};
