/**
 * Fixed Text structure for Light-Mode-Tonal with Surfaces/Containers hierarchy
 * This structure is constant and does not change based on color extraction
 */
export const lightModeTonalTextFixed = {
  Surfaces: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Neutral.Color-9}', type: 'color' as const }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Primary.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Primary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Primary.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Primary.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Primary.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Primary.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Primary.Color-9}', type: 'color' as const }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Secondary.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Secondary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Secondary.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Secondary.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Secondary.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Secondary.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Secondary.Color-9}', type: 'color' as const }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Tertiary.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Tertiary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Tertiary.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Tertiary.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Tertiary.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Tertiary.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Tertiary.Color-9}', type: 'color' as const }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Info.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Info.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Info.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Info.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Info.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Info.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Info.Color-9}', type: 'color' as const }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Success.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Success.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Success.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Success.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Success.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Success.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Success.Color-9}', type: 'color' as const }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Warning.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Warning.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Warning.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Warning.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Warning.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Warning.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Warning.Color-9}', type: 'color' as const }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Error.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Error.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Error.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Error.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Error.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Error.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Error.Color-9}', type: 'color' as const }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' as const },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-2}', type: 'color' as const },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-2}', type: 'color' as const },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' as const },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Surfaces.Hotlink-Visited.Color-9}', type: 'color' as const }
    },
    'BW-Button': {
      'Color-1': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-6': { value: '{Colors.White}', type: 'color' as const },
      'Color-7': { value: '{Colors.White}', type: 'color' as const },
      'Color-8': { value: '{Colors.White}', type: 'color' as const },
      'Color-9': { value: '{Colors.White}', type: 'color' as const },
      'Color-10': { value: '{Colors.White}', type: 'color' as const },
      'Color-11': { value: '{Colors.White}', type: 'color' as const },
      'Color-12': { value: '{Colors.White}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.White}', type: 'color' as const }
    },
    BW: {
      'Color-1': { value: '{Colors.White}', type: 'color' as const },
      'Color-2': { value: '{Colors.White}', type: 'color' as const },
      'Color-3': { value: '{Colors.White}', type: 'color' as const },
      'Color-4': { value: '{Colors.White}', type: 'color' as const },
      'Color-5': { value: '{Colors.White}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Neutral.Color-1}', type: 'color' as const }
    }
  },
  Containers: {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Neutral.Color-9}', type: 'color' as const }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Primary.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Primary.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Primary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Primary.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Primary.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Primary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Primary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Primary.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Primary.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Primary.Color-9}', type: 'color' as const }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Secondary.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Secondary.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Secondary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Secondary.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Secondary.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Secondary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Secondary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Secondary.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Secondary.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Secondary.Color-9}', type: 'color' as const }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Tertiary.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Tertiary.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Tertiary.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Tertiary.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Tertiary.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Tertiary.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Tertiary.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Tertiary.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Tertiary.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Tertiary.Color-9}', type: 'color' as const }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Info.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Info.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Info.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Info.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Info.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Info.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Info.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Info.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Info.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Info.Color-9}', type: 'color' as const }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Success.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Success.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Success.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Success.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Success.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Success.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Success.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Success.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Success.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Success.Color-9}', type: 'color' as const }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Warning.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Warning.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Warning.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Warning.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Warning.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Warning.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Warning.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Warning.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Warning.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Warning.Color-9}', type: 'color' as const }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Error.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Error.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Error.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Error.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Error.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Error.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Error.Color-5}', type: 'color' as const },
      'Color-11': { value: '{Colors.Error.Color-5}', type: 'color' as const },
      'Color-12': { value: '{Colors.Error.Color-5}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Error.Color-9}', type: 'color' as const }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-9}', type: 'color' as const },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-10}', type: 'color' as const },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' as const },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' as const },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' as const },
      'Color-Vibrant': { value: '{Text.Containers.Hotlink-Visited.Color-9}', type: 'color' as const }
    },
    'BW-Button': {
      'Color-1': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-2': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-3': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-4': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-5': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-6': { value: '{Colors.White}', type: 'color' as const },
      'Color-7': { value: '{Colors.White}', type: 'color' as const },
      'Color-8': { value: '{Colors.White}', type: 'color' as const },
      'Color-9': { value: '{Colors.White}', type: 'color' as const },
      'Color-10': { value: '{Colors.White}', type: 'color' as const },
      'Color-11': { value: '{Colors.White}', type: 'color' as const },
      'Color-12': { value: '{Colors.White}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.White}', type: 'color' as const }
    },
    BW: {
      'Color-1': { value: '{Colors.White}', type: 'color' as const },
      'Color-2': { value: '{Colors.White}', type: 'color' as const },
      'Color-3': { value: '{Colors.White}', type: 'color' as const },
      'Color-4': { value: '{Colors.White}', type: 'color' as const },
      'Color-5': { value: '{Colors.White}', type: 'color' as const },
      'Color-6': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-7': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-8': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-9': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-10': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-11': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-12': { value: '{Colors.Neutral.Color-1}', type: 'color' as const },
      'Color-Vibrant': { value: '{Colors.Neutral.Color-1}', type: 'color' as const }
    }
  }
};

// Export as lightModeTextFixed for backward compatibility
export const lightModeTextFixed = lightModeTonalTextFixed;
