/**
 * Static token structures that reference Colors but don't generate new colors
 * These are imported from sample-output.json and should remain unchanged
 */

export { getStaticQuietTokensForLightMode, getStaticQuietTokensForDarkMode } from './staticQuietStructures';

export function getStaticHoverTokens() {
  return {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Neutral.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Neutral.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Neutral.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Neutral.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Neutral.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Neutral.Color-9}', type: 'color' }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Primary.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Primary.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Primary.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Primary.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Primary.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Primary.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Primary.Color-9}', type: 'color' }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Secondary.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Secondary.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Secondary.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Secondary.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Secondary.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Secondary.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Secondary.Color-9}', type: 'color' }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Tertiary.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Tertiary.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Tertiary.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Tertiary.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Tertiary.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Tertiary.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Tertiary.Color-9}', type: 'color' }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Info.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Info.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Info.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Info.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Info.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Info.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Info.Color-9}', type: 'color' }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Success.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Success.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Success.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Success.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Success.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Success.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Success.Color-9}', type: 'color' }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Warning.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Warning.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Warning.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Warning.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Warning.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Warning.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Warning.Color-9}', type: 'color' }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-4': { value: '{Colors.Error.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-6': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-7': { value: '{Colors.Error.Color-8}', type: 'color' },
      'Color-8': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-9': { value: '{Colors.Error.Color-8}', type: 'color' },
      'Color-10': { value: '{Colors.Error.Color-8}', type: 'color' },
      'Color-11': { value: '{Colors.Error.Color-8}', type: 'color' },
      'Color-12': { value: '{Colors.Error.Color-8}', type: 'color' },
      'Color-Vibrant': { value: '{Hover.Error.Color-9}', type: 'color' }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-10}', type: 'color' },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-Vibrant': { value: '{Colors.Hotlink-Visited.Color-10}', type: 'color' }
    },
    BW: {
      'Color-1': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-3': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-4': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-6': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-7': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-8': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-9': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-10': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-11': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-12': { value: '{Colors.Neutral.Color-11}', type: 'color' },
      'Color-Vibrant': { value: '{Active.BW.Color-10}', type: 'color' }
    }
  };
}

export function getStaticActiveTokens() {
  return {
    Neutral: {
      'Color-1': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Neutral.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Neutral.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Neutral.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Neutral.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Neutral.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Neutral.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Neutral.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Neutral.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Neutral.Color-10}', type: 'color' }
    },
    Primary: {
      'Color-1': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Primary.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Primary.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Primary.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Primary.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Primary.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Primary.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Primary.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Primary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Primary.Color-10}', type: 'color' }
    },
    Secondary: {
      'Color-1': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Secondary.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Secondary.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Secondary.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Secondary.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Secondary.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Secondary.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Secondary.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Secondary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Secondary.Color-10}', type: 'color' }
    },
    Tertiary: {
      'Color-1': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Tertiary.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Tertiary.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Tertiary.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Tertiary.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Tertiary.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Tertiary.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Tertiary.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Tertiary.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Tertiary.Color-10}', type: 'color' }
    },
    Info: {
      'Color-1': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Info.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Info.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Info.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Info.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Info.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Info.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Info.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Info.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Info.Color-10}', type: 'color' }
    },
    Success: {
      'Color-1': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Success.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Success.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Success.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Success.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Success.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Success.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Success.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Success.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Success.Color-10}', type: 'color' }
    },
    Warning: {
      'Color-1': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Warning.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Warning.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Warning.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Warning.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Warning.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Warning.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Warning.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Warning.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Warning.Color-10}', type: 'color' }
    },
    Error: {
      'Color-1': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-2': { value: '{Colors.Error.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Error.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Error.Color-3}', type: 'color' },
      'Color-5': { value: '{Colors.Error.Color-6}', type: 'color' },
      'Color-6': { value: '{Colors.Error.Color-8}', type: 'color' },
      'Color-7': { value: '{Colors.Error.Color-9}', type: 'color' },
      'Color-8': { value: '{Colors.Error.Color-6}', type: 'color' },
      'Color-9': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-10': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-11': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-12': { value: '{Colors.Error.Color-7}', type: 'color' },
      'Color-Vibrant': { value: '{Active.Error.Color-10}', type: 'color' }
    },
    'Hotlink-Visited': {
      'Color-1': { value: '{Colors.Hotlink-Visited.Color-3}', type: 'color' },
      'Color-2': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-3': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-4': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-5': { value: '{Colors.Hotlink-Visited.Color-10}', type: 'color' },
      'Color-6': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-7': { value: '{Colors.Hotlink-Visited.Color-4}', type: 'color' },
      'Color-8': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-9': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-10': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-11': { value: '{Colors.Hotlink-Visited.Color-5}', type: 'color' },
      'Color-12': { value: '{Colors.Hotlink-Visited.Color-11}', type: 'color' },
      'Color-Vibrant': { value: '{Colors.Hotlink-Visited.Color-10}', type: 'color' }
    }
  };
}
